In [1]:
import numpy as np
from pandas import DataFrame 

# (a) Logistic Regression from Scratch

In [95]:
X_train = np.array([[0.346,0.780], [0.303,0.439],[0.358 ,0.729],[0.602,0.863],[0.790,0.753],[0.611,0.965]])
Y_train = np.array([0,0,0,1,1,1])

In [96]:
X_test = np.array([[0.959,0.382], [0.750,0.306],[0.395 ,0.760],[0.823, 0.764],[0.761, 0.874],[0.844 ,0.435]])
Y_test = np.array([0,0,0,1,1,1])

In [97]:
def sigmoid(z):
    op = 1 / (1 + np.exp(-z))
    return op

In [98]:
def model(w,X):
    z = np.array(w[0] + w[1]*np.array(X[:,0]) + w[2]*np.array(X[:,1]))
    return sigmoid(z)

In [99]:
def cost(w, X, Y):
    predict = model(w,X)
    res = -1 * sum(Y*np.log(predict) + (1-Y)*np.log(1-predict))
    return res

In [100]:
def gradient(w, X, Y):
    predict = model(w,X)
    g = [0]*3
    g[0] = -1 * sum(Y*(1-predict) - (1-Y)*predict)
    g[1] = -1 * sum(Y*(1-predict)*X[:,0] - (1-Y)*predict*X[:,0])
    g[2] = -1 * sum(Y*(1-predict)*X[:,1] - (1-Y)*predict*X[:,1])
    return g

In [101]:
def descent(new_w, prev_w, learning_rate):
    print(prev_w)
    print(cost(prev_w, X, Y))
    j=0
    while True:
        prev_w = new_w
        w0 = prev_w[0] - learning_rate*gradient(prev_w, X, Y)[0]
        w1 = prev_w[1] - learning_rate*gradient(prev_w, X, Y)[1]
        w2 = prev_w[2] - learning_rate*gradient(prev_w, X, Y)[2]
        new_w = [w0, w1, w2]
        print(new_w)
        print(cost(new_w, X, Y))
        if (new_w[0]-prev_w[0])**2 + (new_w[1]-prev_w[1])**2 + (new_w[2]-prev_w[2])**2 <pow(10,-6):
            return new_w
        if j>100: 
            return new_w
        j+=1

In [102]:
w=[-1,1.5,0.5]

In [103]:
prediction = model(w,X_test)

In [104]:
y_predict = prediction
y_predict

array([0.65237608, 0.56905583, 0.49312543, 0.64942211, 0.64072218,
       0.61857401])

In [105]:
prediction

array([0.65237608, 0.56905583, 0.49312543, 0.64942211, 0.64072218,
       0.61857401])

In [106]:
for i in range(len(prediction)):
    if prediction[i]<=0.5:
        prediction[i]=0
    else:
        prediction[i]=1

In [107]:
prediction

array([1., 1., 0., 1., 1., 1.])

In [56]:
cnt=0
for i in range(len(prediction)):
    if prediction[i] == Y_test[i]:
        cnt+=1
print("Accuracy calculated using Logistic Regression is :" + str(round((cnt/len(prediction)),5)))

Accuracy calculated using Logistic Regression is :0.66667


In [57]:
w = descent(w,w,0.1)

[-1.0189975586353857, 1.5321051772436016, 0.5118120174982301]
3.326448831508982
[-1.0388526375203453, 1.5636107896309686, 0.5228576093831279]
3.3114058492865563
[-1.0593107469109555, 1.5946484560313285, 0.5333332355499049]
3.2965271096860276
[-1.0801863777960774, 1.6253142808171839, 0.5433822290432841]
3.281788407824884
[-1.1013442185787043, 1.6556785484563898, 0.5531092735377986]
3.267176326511796
[-1.1226855313279656, 1.6857927448709404, 0.5625908987432489]
3.2526832147822216
[-1.144138252907387, 1.7156946532286985, 0.5718831033766161]
3.238304509332731
[-1.1656497919903854, 1.745412058549913, 0.5810269005100219]
3.224037303665542
[-1.1871817814049173, 1.774965444676416, 0.5900523567320989]
3.209879582812813
[-1.2087062511848135, 1.8043699599057021, 0.5989815373309483]
3.1958298136108896
[-1.2302028353673278, 1.8336368509452292, 0.6078306556777593]
3.18188672513694
[-1.2516567318558347, 1.862774509817369, 0.6166116429974767]
3.1680491909575133
[-1.2730572114047054, 1.8917892386950252

# (b)

Linear Model: fw(x1, x2) = w0 + w1 * x1 + w2 * x2

Logistic Regression Function : 1 / (1 + e ^ (-fw(x1, x2)))

f(x1,x2) = - 1 + 1.5 * x1 + 0.5 * x2

# i) Logistic Model and Cross-Entropy Error Function

Logistic Model : P(y_hat = 1|x1, x2) = sigmoid(f(x)) = 1 / 1 + e-(- 1 + 1.5 * x1 + 0.5 * x2)

Cross-entropy Error Function :  

=> -[y * log(y_predict) + (1−y) * log(1−y_predict)] 

=> -[y * log(sigmoid(f(x)) + (1-y) * log(1 - sigmoid(f(x)))]

=> -[y * log(sigmoid(- 1 + 1.5 * x1 + 0.5 * x2) + (1-y) * log(1 - sigmoid(- 1 + 1.5 * x1 + 0.5 * x2)]

In [72]:
cross_entropy = -((Y_train * np.log(y_predict)) + ((1-Y_train) * np.log(1 - y_predict)))
cross_entropy

array([1.05663407, 0.84177673, 0.67949171, 0.43167237, 0.44515933,
       0.48033844])

# ii)  Updated Logistic Regression Model.

In [73]:
def update(new_w, prev_w, learning_rate):
    print(prev_w)
    print(cost(prev_w, X, Y))
    j=0
    while True:
        prev_w = new_w
        w0 = prev_w[0] - learning_rate*gradient(prev_w, X, Y)[0]
        w1 = prev_w[1] - learning_rate*gradient(prev_w, X, Y)[1]
        w2 = prev_w[2] - learning_rate*gradient(prev_w, X, Y)[2]
        new_w = [w0, w1, w2]
        print(new_w)
        print(cost(new_w, X, Y))
        if (new_w[0]-prev_w[0])**2 + (new_w[1]-prev_w[1])**2 + (new_w[2]-prev_w[2])**2 <pow(10,-6):
            return new_w
        if j<=1: 
            return new_w
        j+=1

In [74]:
w = update(w,w,0.1)

[-1, 1.5, 0.5]
3.341700478528591
[-1.0189975586353857, 1.5321051772436016, 0.5118120174982301]
3.326448831508982


# iii) Accuracy, Precision and Recall calculation

In [110]:
true_pos=true_neg=false_pos=false_neg=0
for i in range (len(y_predict)):
    if y_predict[i]==0 and Y_test[i]==0: 
        true_pos+=1
    elif y_predict[i]==0 and Y_test[i]==1: 
        false_pos+=1
    elif y_predict[i]==1 and Y_test[i]==0: 
        false_neg+=1
    elif y_predict[i]==1 and Y_test[i]==1: 
        true_neg+=1

In [123]:
print("Accuracy:",((true_pos+true_neg)/(true_pos+true_neg+false_neg+false_pos)))

Accuracy: 0.6666666666666666


In [125]:
print("Precision:",true_pos/(true_pos+false_pos))

Precision: 1.0


In [113]:
print("Recall:",true_pos/(true_pos+false_neg))

Recall: 0.3333333333333333
